name: Manual destroy

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'eu-central-1'
      environment:
        description: 'Environment'
        required: true
        default: 'production'

jobs:
  destroy:
    name: Delete stack from AWS
    runs-on: [self-hosted, builder]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.region}}

    - name: Destroy stack
      run: |
        aws cloudformation delete-stack \
          --stack-name stack-to-do-app-${{ github.event.inputs.environment }}
